In [48]:
import numpy as np
a = np.arange(15)
print(a)
a= a.reshape(5,3)

print(a.shape)
print(a.ndim)

a.dtype.name
a.itemsize

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(5, 3)
2


8

In [11]:
random = [1, 3, 5, 2, 4]
#random_sort = sorted(random)

def smallest(l, num):
    random_sort = sorted(l)
    return random_sort[num-1] 

smallest(random, 3)

3

In [27]:
class Deck:
    def __init__(self, card):
        #for i in range(1, 11):
        #    card = [i+'H', i+'S', i+'C', i+'D']
        if card[0] not in '1234567890JQK' and card[1] not in 'HDCS':
            print("ERROR")
        else:
            self.cards = card
    def __str__(self):
        return str(self.cards)

In [28]:
card = Deck('1H')
print(card)

1H


In [18]:
import numpy as np
from timeit import timeit
from functools import reduce

#Sudoku Puzzle
first = [7, 6, 9, 8, 0, 0, 3, 0, 0]
first = list((7, 6, 9, 8, 0, 0, 3, 0, 0))

#test = "my_list = [0 for i in range(50)]"
#print(timeit(test))

test = "first = [7, 6, 9, 8, 0, 0, 3, 0, 0]"
print("USING SQUARE BRACKETS: ", timeit(test)) #this take shorter amount of time. 

test = "first = list((7, 6, 9, 8, 0, 0, 3, 0, 0))"
print("USING LIST FUNCTION: ", timeit(test)) #this takes longer to do

second = [4,0,0,0,0,0,0,7,0]
third = [0,0,0,7,0,5,0,0,6]
fourth = [0,9,0, 0,7,0, 0,0,2]
fifth = [0,0,3, 0,7,0, 0,0,2]
sixth = [6,0,0, 0,8,0, 0,4,0]
seventh = [1,0,0, 2,0,6, 0,0,0]
eighth = [0,3,0, 0,0,0, 0,0,4]
ninth = [0,0,2,0,0,8,7,6,1]

#Comment out Mulitple Lines of Code == Ctrl + /
# second = [[4,0,0], [0,0,0], [0,7,0]]
# third = [[0,0,0], [7,0,5], [0,0,6]]
# fourth = [[0,9,0], [0,7,0], [0,0,2]]
# fifth = [[0,0,3], [0,7,0], [0,0,2]]
# sixth = [[6,0,0], [0,8,0], [0,4,0]]
# seventh = [[1,0,0], [2,0,6], [0,0,0]]
# eighth = [[0,3,0], [0,0,0], [0,0,4]]
# ninth = [[0,0,2], [0,0,8], [7,6,1]]

box1= first[0], second[0], third[0]
sudoku_puzzle = np.array([first, second, third, fourth, fifth, sixth, seventh, eighth, ninth])

def solver_python(sudoku_puzzle):

    numbers = np.arange(1,10)
    i, j = np.where(sudoku_puzzle==0)
    #print(i.size) #52
    #print(j.size) #52

    i,j = i[0], j[0]

    row = sudoku_puzzle[i, :]
    col = sudoku_puzzle[:, j]

    square = sudoku_puzzle[:3,:3]
    #print(row)
    #print(col)
    print("Square: \n", square)
    #print(j)

    sqr = sudoku_puzzle[(i//3)*3:(3+(i//3)*3),(j//3)*3:(3+(j//3)*3)]
    values = np.setdiff1d(numbers,reduce(np.union1d,(row,col,sqr)))

    grid_temp = np.copy(sudoku_puzzle) 

    for value in values:
        grid_temp[i,j] = value
        test = solver_python(grid_temp)
        if (test[0]):
            return(test)
print(solver_python(sudoku_puzzle))

USING SQUARE BRACKETS:  0.10122364199992262
USING LIST FUNCTION:  0.17315125199991144
Square: 
 [[7 6 9]
 [4 0 0]
 [0 0 0]]
Square: 
 [[7 6 9]
 [4 0 0]
 [0 0 0]]
Square: 
 [[7 6 9]
 [4 0 0]
 [0 0 0]]
Square: 
 [[7 6 9]
 [4 0 0]
 [0 0 0]]


TypeError: 'NoneType' object is not subscriptable

In [27]:
mat = np.array([[0,0,0],[1,0,0]])
np.where(mat==0)


(array([0, 0, 0, 1, 1]), array([0, 1, 2, 1, 2]))

In [70]:
first = [7, 6, 9, 8, 0, 0, 3, 0, 0]
second = [4,0,0,0,0,0,0,7,0]
third = [0,0,0,7,0,5,0,0,6]
fourth = [0,9,0, 0,7,0, 0,0,2]
fifth = [0,0,3, 0,7,0, 0,0,2]
sixth = [6,0,0, 0,8,0, 0,4,0]
seventh = [1,0,0, 2,0,6, 0,0,0]
eighth = [0,3,0, 0,0,0, 0,0,4]
ninth = [0,0,2,0,0,8,7,6,1]

bam = first+second+third+fourth+fifth+sixth+seventh+eighth+ninth
sudoku1= np.array([bam]).reshape(9,9)
print("REVISED SUDOKU: \n", sudoku1)

#colum = sudoku[:, 0:2]
#print(colum)

sudoku = np.array([first, second, third, fourth, fifth, sixth, seventh, eighth, ninth])
#print(sudoku)
print(sudoku[0:3, 0:3])
np.where(sudoku==0)

fullSet = {1, 2, 3, 4, 5, 6, 7, 8, 9}
for row in range(0,9):
    for column in range(0,9):
        if sudoku1[row][column] == 0:
            r = fullSet - set(sudoku[row])
            c = r - set(sudoku[:, column])
            rowStart = (row//3) * 3
            colStart = (column//3) * 3
            P = np.copy(sudoku)
            P = P + 1
            print(P)
            P[row][column] = list(c - set(sudoku[rowStart:rowStart+3, colStart:colStart+3].flatten()))
            #print(list(c - set(sudoku[rowStart:rowStart+3, colStart:colStart+3].flatten())))

            

REVISED SUDOKU: 
 [[7 6 9 8 0 0 3 0 0]
 [4 0 0 0 0 0 0 7 0]
 [0 0 0 7 0 5 0 0 6]
 [0 9 0 0 7 0 0 0 2]
 [0 0 3 0 7 0 0 0 2]
 [6 0 0 0 8 0 0 4 0]
 [1 0 0 2 0 6 0 0 0]
 [0 3 0 0 0 0 0 0 4]
 [0 0 2 0 0 8 7 6 1]]
[[7 6 9]
 [4 0 0]
 [0 0 0]]
[[ 8  7 10  9  1  1  4  1  1]
 [ 5  1  1  1  1  1  1  8  1]
 [ 1  1  1  8  1  6  1  1  7]
 [ 1 10  1  1  8  1  1  1  3]
 [ 1  1  4  1  8  1  1  1  3]
 [ 7  1  1  1  9  1  1  5  1]
 [ 2  1  1  3  1  7  1  1  1]
 [ 1  4  1  1  1  1  1  1  5]
 [ 1  1  3  1  1  9  8  7  2]]


ValueError: setting an array element with a sequence.

In [147]:
import numpy as np
import random

first =  [7,6,9,8,0,0,3,0,0]
second = [4,0,0,0,0,0,0,7,0]
third =  [0,0,0,7,0,5,0,0,6]
fourth = [0,9,0,0,7,0,0,0,2]
fifth =  [0,0,3,0,7,0,0,0,2]
sixth =  [6,0,0,0,8,0,0,4,0]
seventh= [1,0,0,2,0,6,0,0,0]
eighth = [0,3,0,0,0,0,0,0,4]
ninth =  [0,0,2,0,0,8,7,6,1]

bam = first+second+third+fourth+fifth+sixth+seventh+eighth+ninth
sudoku1= np.array([bam]).reshape(9,9)


nine = np.array([1,2,3,4,5,6,7,8,9])
box = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

boxes = []
rows = []
columns = []
for row in range(len(sudoku1)):
    rows.append(np.setdiff1d(nine, sudoku1[row]))
    columns.append(np.setdiff1d(nine, sudoku1[:,row]))
    for column in range(len(sudoku1)-2):
        boxes.append(np.setdiff1d(box, sudoku1[0+row:row+3,0+column:column+3]))
# for i in range(len(sudoku1)):
#     for j in range(len(sudoku1)):
#         if sudoku1[i][j] == 0:
#             print(i,j)

# for i in range(len(sudoku1)):
#     for j in range(len(sudoku1)-2):
#         #print(sudoku1[0+i:i+3,0+j:j+3])
#         print(np.setdiff1d(box, sudoku1[0+i:i+3,0+j:j+3]))

print(boxes)
print(np.minimum([2, 3, 4], [1, 5, 2]))

rows[0] = list(rows[0])
for i in range(len(rows[0])):
    random.shuffle(rows[0])
    element = rows[0].pop()
    print(element)
    for j in range(len(sudoku1)):
        if sudoku1[i][j] == 0:
            print(np.where(sudoku1[0]==0, element, sudoku1[0]))

#print(np.where(sudoku1[i][j]==0, random.choice(rows[0]), sudoku1[0]))
#print(sudoku1)

# for i in range(len(sudoku1)):
#     for j in range(len(sudoku1)):
#         if sudoku1[i][j] == 0:
#             print(sudoku1[i][j])

[array([1, 2, 3, 5, 8]), array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 6, 9]), array([1, 2, 4, 6, 7, 8, 9]), array([1, 2, 4, 6, 8, 9]), array([1, 2, 4, 5, 8, 9]), array([1, 2, 3, 5, 6, 7, 8]), array([1, 2, 3, 4, 5, 6, 8]), array([1, 2, 3, 4, 5, 6, 8, 9]), array([1, 2, 3, 4, 6, 8, 9]), array([1, 2, 3, 4, 6, 8, 9]), array([1, 2, 3, 4, 6, 8, 9]), array([1, 3, 4, 5, 8, 9]), array([1, 2, 4, 5, 6, 7, 8]), array([1, 2, 4, 5, 6, 8]), array([1, 2, 4, 5, 6, 8, 9]), array([1, 2, 3, 4, 6, 8, 9]), array([1, 2, 3, 4, 6, 8, 9]), array([1, 2, 3, 4, 6, 7, 8, 9]), array([1, 3, 4, 5, 7, 8, 9]), array([1, 2, 4, 5, 7, 8]), array([1, 2, 4, 5, 6, 7, 8]), array([1, 2, 4, 5, 6, 9]), array([1, 2, 3, 4, 5, 6, 9]), array([1, 2, 3, 4, 5, 6, 9]), array([1, 2, 3, 5, 6, 7, 8, 9]), array([1, 3, 5, 6, 7, 8, 9]), array([2, 4, 5, 7, 8, 9]), array([1, 4, 5, 6, 7, 8, 9]), array([1, 4, 5, 6, 9]), array([1, 3, 4, 5, 9]), array([1, 2, 3, 4, 5, 9]), array([1, 2, 3, 5, 7, 8, 9]), array([1, 3, 5, 6, 7, 8,